### PR TITLE
chore: replace deprecated `COMPOSER_TOKEN` with `GITHUB_TOKEN`

### PR DESCRIPTION
**Pull request by datamweb**
see https://github.com/codeigniter4/shield/pull/602

### CODE REVIEW

**Comment by datamweb** [comment]
@kenjis I tried to fix error [psalm error](https://github.com/codeigniter4/settings/actions/runs/3984651256/jobs/6831102637), but I'm not sure, please review.
```console
Warning: "findUnusedBaselineEntry" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.
Warning: "findUnusedCode" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.
Target PHP version: 7.4 (inferred from composer.json) Enabled extensions: .
Scanning files...
Deprecation: Psalm stubs for ext-apcu loaded using legacy way. Instead, please declare ext-apcu as dependency in composer.json or use <enableExtensions> and/or <disableExtensions> directives in Psalm config.
Deprecation: Psalm stubs for ext-redis loaded using legacy way. Instead, please declare ext-redis as dependency in composer.json or use <enableExtensions> and/or <disableExtensions> directives in Psalm config.
Analyzing files...

░░░░░░E░░░░░░░

ERROR: ReservedWord - src/Handlers/DatabaseHandler.php:173:31 - 'resource' is a reserved word (see https://psalm.dev/095)
        if (is_bool($result = $query->get())) {


------------------------------
1 errors found
------------------------------
87 other issues found.
You can display them with --show-info=true
------------------------------
Psalm can automatically fix 30 of these issues.
Run Psalm again with 
--alter --issues=MissingReturnType --dry-run
to see what it can fix.
------------------------------

Checks took 3.43 seconds and used 457.239MB of memory
Psalm was able to infer types for 90.97[13](https://github.com/codeigniter4/settings/actions/runs/3984651256/jobs/6831102637#step:9:14)% of the codebase
Error: Process completed with exit code 2.
```

**Comment by kenjis** [comment]
@datamweb It is reported in https://github.com/codeigniter4/settings/actions/runs/4075126980/jobs/7021112053
but the psalm error is not reported now.

**Comment by kenjis** [comment]
It seems it is https://github.com/vimeo/psalm/issues/2625

**Review by kenjis — APPROVED** [review]

**Review by MGatner — APPROVED** [review]
Thanks!

**Pull request merged**
